#import "../_shared/preamble.typ": compendium-preamble, title-page

#compendium-preamble(
  title: "Vastu and Ecological Design",
  subtitle: "Field Dive",
  version: "1.0 — converted from markdown",
)

#title-page(
  title: "Vastu and Ecological Design",
  subtitle: "The 108-pada mandala as landscape architecture",
  volume: "COHERENCE ATLAS · FIELD DIVE VI",
  version: "1.0 · April 2026",
)

_Converted from `research/research_vastu_mandala.md`._

#pagebreak()

= Vāstu Puruṣa Maṇḍala: Comparative, Coordinate-Based Report from Mānasāra, Mānuṣyālaya Candrikā, Māyamata, and Bṛhat Saṃhitā


== Executive summary


The *81-pada (9×9) Vāstu Puruṣa Maṇḍala* (“Paramasāyika”) is described in multiple classical sources as a *grid procedure* (draw 10 lines each way to yield 81 squares) and as a *deity-allocation schema* in which (at minimum) *32 deities occupy the perimeter squares* and an additional set of *inner deities—including a central Brahmā region—occupy interior squares*. The *Bṛhat Saṃhitā*’s Vāstuvidyā chapter provides the most explicit *square-numbered placements* for both perimeter (32) and inner deities and also explains how these deities correspond to *the body-points of the Vāstupuruṣa*. citeturn47view4turn47view0turn48view0

There are *real source-variations* in (a) *which deity is placed at certain boundary positions* (e.g., the first eastern/perimeter position is *Śikhi/Agni* in *Bṛhat Saṃhitā* vs. *Īśa/Īśāna* in the Mānuṣyālaya Candrikā summary tradition), and (b) *the identity-set for the 12 inner deities* (the *Bṛhat Saṃhitā* list differs substantially from the Mānuṣyālaya Candrikā list). The Mānasāra tradition further records explicit disagreements across authorities (including the *Māyamata*) for several assignments. citeturn40view0turn15view2turn14view1

For *marma (vital) avoidance*, the Mānuṣyālaya Candrikā commentary tradition is unusually explicit: in the 81-pada layout it describes (i) *ten “nāḍī” lines to east and ten to north*, (ii) special *rajju (diagonal) lines*, and (iii) *100 marma-sthāna* generated by intersections of major sūtra-lines—explicitly declaring them *to be avoided for walls/columns* and giving a classical mitigation rule (a shift of ~1/24 of a pada from the marma-sūtra) plus a ritual remedy. citeturn39view0turn49view0

For *Āyādi Ṣaḍvarga*, the Mānuṣyālaya Candrikā commentary preserves a full *formula set* (expressed as multipliers and divisors on a house’s “paridhi”/perimeter or combined measures), including: *Yoni remainder (÷8), Vyaya remainder (÷14; and an alternate tradition), Āya remainder (÷12), Nakṣatra remainder (÷27), Tithi remainder (÷30), and Vāra remainder (÷7)*. It explicitly notes cross-attestation: “Mayādi (Maya, i.e., the Mayamata tradition) and others give formulas; Manasāra and Sakalādhikāra also include these methods.” citeturn50view2

Finally, *tālamāna* is treated as a *module system* anchored to the human patron/householder: the Mānuṣyālaya Candrikā commentary states that the *householder’s height is taken as one “tāla”*, and that *daṇḍa measures* (as 8-, 9-, or 10-tāla daṇḍa types) are used for proportional planning (e.g., *vīthī* widths and boundary/mandala banding). citeturn49view0turn50view2

== Text corpus, editions, and methodological notes


This report prioritizes directly citable passages from accessible witnesses of the four requested source-works, with clear flags where a detail is *not fully specified* in the cited passage.

The *Bṛhat Saṃhitā* material is taken from the *Vāstuvidyā* chapter in a bilingual pipeline: (a) an English translation stream that explicitly enumerates square numbers and deities, and (b) the Sanskrit edition view (same chapter, Sanskrit numbering) showing the base verses for grid division and deity enumeration. citeturn47view4turn48view0

The *Mānuṣyālaya Candrikā* material is drawn from an edition with Sanskrit verse citations and a running explanatory commentary (in Hindi), which is valuable here because it (i) transmits the *outer-32 and inner-deity lists as memorized ślokas*, (ii) provides *explicit Āyādi arithmetic formulas* in a compact list, and (iii) explains *marma* generation and taboo (avoid walls/columns on marma). citeturn40view0turn39view0turn50view2turn49view0

The *Mānasāra* material is cited from a full-text “Architecture of Manasara” transcription that includes (a) the description of the 81-pada plan’s line-drawing, (b) a long, stepwise deity assignment sequence for the frog-shaped plan tradition, and (c) an editorial note explicitly listing *differences* between this description and other authorities (including the Mayamata and others). It also includes the well-known outer “demoness” placements beyond the corners. citeturn15view0turn15view4turn14view1

Direct, line-citable *Māyamata / Mayamata* passages on deity-by-square placement were not reliably extractable in this session; consequently, Mayamata is integrated here through (a) explicit Mayamata citations preserved inside Mānuṣyālaya Candrikā commentary (including the famous “1 to 1024 padas” range and the list of 32 plan-names), and (b) explicit Mayamata verse-references and cross-authority comparison notes transmitted in the Mānasāra witness. This is flagged wherever it affects the completeness of “Mayamata-specific” position claims. citeturn49view0turn14view1turn15view4

== Mandala geometry and coordinate conventions used in this report


=== Classical grid definition


The *Bṛhat Saṃhitā* describes the Paramasāyika procedure: *divide the house-ground into 81 squares using 10 lines east–west and 10 lines north–south*, with *32 deities on the 32 exterior squares* and *13 “inner” placements* described next. citeturn47view4turn48view0

The Mānuṣyālaya Candrikā commentary likewise treats the Paramasāyika as *“ekāśītipada / 81-pada”*, gives proportional advice for sūtra/rajju subdivision across 81/100/64 options, and explicitly situates deity-placement and marma construction as part of padavinyāsa practice. citeturn49view0turn39view0

=== Coordinate system


To make every placement computable and comparable across sources, I use a standard *north-up grid*:

- The maṇḍala is a 9×9 lattice of equal *padas*.
- Coordinates are *(x, y)* where *x = 1..9* (west→east) and *y = 1..9* (south→north).
- Corners: SW=(1,1), SE=(9,1), NW=(1,9), NE=(9,9).

For cross-referencing the *Bṛhat Saṃhitā* square numbers, note that its translation stream supplies *square indices 1..81* in a consistent 9×9 numbering scheme (also used for the central 3×3 Brahmā block). citeturn47view4turn47view0

```mermaid
flowchart TB
  A["9×9 Paramasāyika grid\nCoordinates: (x,y)\nx: 1→9 (W→E)\ny: 1→9 (S→N)"] --> B["Perimeter squares (32): x∈{1,9} or y∈{1,9}"]
  A --> C["Interior: includes Brahmā-sthāna (central 3×3 = 9 padas)"]
  C --> D["Other inner deities vary by text (e.g., Bṛhat Saṃhitā vs. Mānuṣyālaya Candrikā)"]
```

== Deity placement datasets


=== Perimeter deity list with exact coordinates


The *Bṛhat Saṃhitā* explicitly enumerates the *32 perimeter deities* by listing the deities occupying the eight squares along each side (excluding the “far” corner which begins the next side’s count). citeturn47view4turn47view0

Because the Bṛhat Saṃhitā translation provides square numbers for each perimeter deity, this table gives: *zone*, *deity*, and *(x,y)* coordinate.

#table(
  columns: 4,
  [*Perimeter zone (side run)*], [*Bṛhat Saṃhitā square\#*], [*Deity (English transliteration)*], [*(x,y)*],
  [East edge, from NE down (excluding SE corner)], [1], [Agni / Śikhi], [(9,9)],
  [], [2], [Parjanya], [(9,8)],
  [], [3], [Jayanta], [(9,7)],
  [], [4], [Indra], [(9,6)],
  [], [5], [Sūrya], [(9,5)],
  [], [6], [Satyā], [(9,4)],
  [], [7], [Bhṛśa], [(9,3)],
  [], [8], [Antarikṣa], [(9,2)],
  [South edge, from SE westward (excluding SW corner)], [9], [Vāyu], [(9,1)],
  [], [18], [Pūṣa], [(8,1)],
  [], [27], [Vitatha], [(7,1)],
  [], [36], [Bṛhatkṣata], [(6,1)],
  [], [45], [Yama], [(5,1)],
  [], [54], [Gandharva], [(4,1)],
  [], [63], [Bhṛṅgarāja], [(3,1)],
  [], [72], [Mṛga], [(2,1)],
  [West edge, from SW up (excluding NW corner)], [81], [Pitṛ], [(1,1)],
  [], [80], [Dauvārika], [(1,2)],
  [], [79], [Sugrīva], [(1,3)],
  [], [78], [Kusumadanta], [(1,4)],
  [], [77], [Varuṇa], [(1,5)],
  [], [76], [Asura], [(1,6)],
  [], [75], [Śeṣa], [(1,7)],
  [], [74], [Pāpayakṣmā], [(1,8)],
  [North edge, from NW eastward (excluding NE corner)], [73], [Roga], [(1,9)],
  [], [64], [Ahi], [(2,9)],
  [], [55], [Mukhya], [(3,9)],
  [], [46], [Bhallāṭa], [(4,9)],
  [], [37], [Soma], [(5,9)],
  [], [28], [Bhujaga], [(6,9)],
  [], [19], [Aditi], [(7,9)],
  [], [10], [Diti], [(8,9)],
)



Source basis: Bṛhat Saṃhitā (Vāstuvidyā) explicit square-number list. citeturn47view4turn47view0

=== Inner deity list with exact coordinates


In the Bṛhat Saṃhitā’s 81-square model, the “inner placements” relevant to the frequently cited “32 + 12 (+ Brahmā)” scheme are:

- *Brahmā* occupies *the central 3×3 block* (9 squares). citeturn47view0turn47view4
- *12 additional inner deities* are placed at specific interior squares (four inner corners + eight around Brahmā as described). citeturn47view0turn47view4

#table(
  columns: 4,
  [*Inner deity (Bṛhat Saṃhitā)*], [*Bṛhat Saṃhitā square\#*], [*Position clue in text*], [*(x,y)*],
  [Āpa], [11], [“inner north-eastern square”], [(8,8)],
  [Sāvitra], [17], [“inner south-eastern square”], [(8,2)],
  [Java], [71], [“inner south-western square”], [(2,2)],
  [Rudra], [65], [“inner north-western square”], [(2,8)],
  [Aryaman], [23], [“due east of Brahmā”], [(7,5)],
  [Savitā], [25], [alternate-square ring around Brahmā], [(7,3)],
  [Vivasvān], [43], [alternate-square ring around Brahmā], [(5,3)],
  [Indra], [61], [alternate-square ring around Brahmā], [(3,3)],
  [Mitra], [59], [alternate-square ring around Brahmā], [(3,5)],
  [Rājayakṣmā], [57], [alternate-square ring around Brahmā], [(3,7)],
  [Pṛthvīdhara], [39], [alternate-square ring around Brahmā], [(5,7)],
  [Āpavatsa], [21], [alternate-square ring around Brahmā], [(7,7)],
)



Source basis: Bṛhat Saṃhitā (Vāstuvidyā) square-number placements. citeturn47view0turn47view4turn48view0

=== Source variations across Mānuṣyālaya Candrikā, Mānasāra, and Mayamata traditions


The Mānuṣyālaya Candrikā tradition preserves a *compact mnemonic list* for the outer 32 and a different list for inner deities:

- It explicitly states “outside: 32 deities; inside enclosure: inner deities; center: Brahmā,” giving the full outer perimeter sequence in two ślokas and then naming a distinct inner set (including Indrajit, Śiva/Śivajit, Bhūbhṛt) that is *not the Bṛhat Saṃhitā inner set*. citeturn40view0turn40view2
- It also discusses an “outer beyond the mandala” set of eight (*deva-grahas* / corner spirits) and explicitly notes outside-corner demoness/guardian placements (Charakī, Vidārī, Pūtanā, Pāparākṣasī, etc.). citeturn40view3turn40view4

The Mānasāra witness likewise assigns corner/outside entities and records cross-authority disagreements:

- It describes the 81-pada Paramaśāyikā line-drawing and proceeds through deity assignments, with explicit corner/outside demoness placements (e.g., Cārakī, Vidārī, Pūtanā, Pāparākṣasī located outside the corners). citeturn15view0turn14view1
- It contains a long editorial note listing how *other authorities (explicitly including the Mayamata)* swap or reposition several deities (Udita/Jayanta/Antarikṣa/Vitatha/Mṛga/Sugrīva/Godhā, etc.), explicitly acknowledging systematic disagreement. citeturn14view1turn15view4

Because the Mayamata’s own chapter text was not directly citable here at the level needed for a full “deity-per-square” extraction, I treat Mayamata-specific placements as *“indirectly attested via cross-citation”* through Mānasāra and Mānuṣyālaya Candrikā commentary, not as a fully independent placement-table.

== Marma, sūtra-lines, and the requested nine primary marma-sthāna


=== What the sources explicitly say about “marma” in the 81-pada scheme


The Mānuṣyālaya Candrikā commentary provides unusually explicit structural rules:

- For the *81-pada* layout it states: draw *ten east-directed and ten north-directed “nāḍī” lines*; identify *rajju* diagonals; and derive *100 marma-sthāna* from intersections (“yoga/sampāta”) of major sūtra counts (including 8/6/5/4 intersections), explicitly stating these are *to be avoided for walls/columns*. citeturn39view0turn49view0
- It gives a mitigation rule: if construction lines are offset from a marma-sūtra by approximately *1/24 of a pada* (expressed as “pada-bhāskara-aṃśa-dala-mātra”), the marma is not “pierced” by columns/walls; it also mentions a ritual remedy (burying gold heads of animals like buffalo/lion/elephant/tortoise/boar) if marma-doṣa is present. citeturn39view0turn49view0

=== Interpreting the requested “nine primary marma-sthāna”


None of the cited passages in these four sources explicitly labels a set of *exactly nine* points as “primary marma.” What *is* explicit is:

- In the 81-pada model, *Brahmā occupies a 3×3 (nine-square) central region*. citeturn47view0turn47view4turn40view0
- The Bṛhat Saṃhitā warns that the householder should take particular care of the “seat of Brahmā,” because defilement produces misery. citeturn46view0

Given your requirement for *nine* marma-sthāna with grid coordinates, the most text-grounded “nine” candidate is the *nine-square Brahmā-sthāna*, treated in practice as the most sensitive interior region and explicitly described as Brahmā’s occupancy zone.

=== Table of nine Brahmā-sthāna squares as “primary marma-square candidates”


#table(
  columns: 4,
  [*Marma candidate*], [*Bṛhat Saṃhitā square\#*], [*(x,y)*], [*Classical description anchor*],
  [Brahmā-sthāna square], [31], [(6,6)], [central 3×3 occupied by Brahmā citeturn47view0turn47view4],
  [Brahmā-sthāna square], [32], [(6,5)], [same citeturn47view0turn47view4],
  [Brahmā-sthāna square], [33], [(6,4)], [same citeturn47view0turn47view4],
  [Brahmā-sthāna square], [40], [(5,6)], [same citeturn47view0turn47view4],
  [Brahmā-sthāna “center”], [41], [(5,5)], [same; “seat of Brahmā” care warning citeturn47view0turn46view0],
  [Brahmā-sthāna square], [42], [(5,4)], [same citeturn47view0turn47view4],
  [Brahmā-sthāna square], [49], [(4,6)], [same citeturn47view0turn47view4],
  [Brahmā-sthāna square], [50], [(4,5)], [same citeturn47view0turn47view4],
  [Brahmā-sthāna square], [51], [(4,4)], [same citeturn47view0turn47view4],
)



Important caveat: this table treats the nine-square Brahmā region as the best-defined “nine” grid-sensitive set; the Mānuṣyālaya Candrikā marma doctrine simultaneously defines *100 marma points* based on sūtra intersections, which operate as *point* nodes rather than “nine squares.” citeturn39view0turn49view0

== Āyādi Ṣaḍvarga formulas and worked example


=== Classical formula set as transmitted in Mānuṣyālaya Candrikā commentary


The Mānuṣyālaya Candrikā commentary gives the “Ayādi” extraction as remainder arithmetic on a perimeter-like total (“परिधि / paridhi”) and lists each divisor (and multipliers where specified), explicitly calling these “yōni, vyaya, āya, nakṣatra/ṛkṣa, tithi, vāra,” and noting cross-attestation in Mayamata (“Mayādi”), Mānasāra, and Sakalādhikāra traditions. citeturn50view2

Let *P* = the operative perimeter/measure used in the text’s “peridhi” sense (often taken as *2(L+W)* in practice; the commentary frames it as a combined measure set, “iṣṭa-ātāna-vitāna-māna-nicaya”). citeturn50view2

The formulas (as given in the excerpt) are:

- *Yoni*: multiply by *3*, divide by *8*, take remainder ⇒ yoni-index. citeturn50view2
- *Vyaya*: divide by *14* (muni-yuga), take remainder ⇒ vyaya-index. The commentary also preserves an *alternate vyaya* computation tradition (not fully expanded in the excerpt but flagged as “vyaya’s alternative side/ पक्षान्तर”). citeturn50view2
- *Āya*: multiply by *8*, divide by *12*, take remainder ⇒ āya-index. citeturn50view2
- *Nakṣatra / Ṛkṣa*: multiply by *8*, divide by *27*, take remainder ⇒ nakṣatra-index. citeturn50view2
- *Tithi*: multiply by *8*, divide by *30*, take remainder ⇒ tithi-index. citeturn50view2
- *Vāra*: divide by *7*, take remainder ⇒ weekday-index. citeturn50view2

The same passage also links yoni symbolism to directional/planetary discussions elsewhere in the commentary tradition (see matrix notes below). citeturn50view2turn37view3

=== Worked example


Assumption (explicit): the excerpted formula-set operates on *P = 2(L+W)* (a standard “perimeter” measure). The cited passage uses the term “परिधि / paridhi” and describes applying divisors to a combined dimension set; it does not, in the excerpted lines, explicitly define whether P is pure perimeter, half-perimeter, or another compound. citeturn50view2

Assume a sample plot/building rectangle:
- Length *L = 30 hasta*
- Width *W = 20 hasta*
- Then *P = 2(L+W) = 2(50) = 100 hasta*

Now compute:

==== Yoni

Compute *(3P) mod 8*
3P = 300
300 ÷ 8 = 37 remainder *4*
So *Yoni index = 4*. citeturn50view2

==== Vyaya

Compute *P mod 14*
100 ÷ 14 = 7 remainder *2*
So *Vyaya index = 2*. citeturn50view2

==== Āya

Compute *(8P) mod 12*
8P = 800
800 ÷ 12 = 66 remainder *8*
So *Āya index = 8*. citeturn50view2

==== Nakṣatra

Compute *(8P) mod 27*
8P = 800
800 ÷ 27 = 29 remainder *17*
So *Nakṣatra index = 17*. citeturn50view2

==== Tithi

Compute *(8P) mod 30*
8P = 800
800 ÷ 30 = 26 remainder *20*
So *Tithi index = 20*. citeturn50view2

==== Vāra

Compute *P mod 7*
100 ÷ 7 = 14 remainder *2*
So *Vāra index = 2*. citeturn50view2

==== Comparative logic (Āya vs Vyaya)

The Mānuṣyālaya Candrikā commentary explicitly frames *prosperity* logic as *Āya exceeding Vyaya* being wealth-producing, and the reverse being inauspicious. In our numeric example: Āya-index (8) > Vyaya-index (2), thus *“āya exceeds vyaya”* in the simplistic remainder-space sense. citeturn37view1

=== Āyādi Ṣaḍvarga calculation flowchart


```mermaid
flowchart TD
  A["Input building/plot dimensions (L,W)\nChoose measuring unit"] --> B["Compute operative P (peridhi)\n(assumption: P=2(L+W))"]
  B --> C["Yoni = (3P) mod 8"]
  B --> D["Vyaya = P mod 14\n(also note alternate tradition)"]
  B --> E["Aya = (8P) mod 12"]
  B --> F["Nakshatra = (8P) mod 27"]
  B --> G["Tithi = (8P) mod 30"]
  B --> H["Vara = P mod 7"]
  C --> I["Map remainder→category\n(8-fold yoni sets)"]
  F --> J["Map remainder→27 nakshatras"]
  G --> K["Map remainder→30 tithis"]
  H --> L["Map remainder→7 weekdays"]
  D --> M["Compare Aya vs Vyaya\n(interpretive rule)"]
```

== Tālamāna proportional system, sample proportional layouts, and measurement table


=== Classical tālamāna rule as stated in Mānuṣyālaya Candrikā tradition


The Mānuṣyālaya Candrikā commentary defines *tāla* as the *householder’s (gṛhakartṛ-puruṣa) height*, and states that *daṇḍa* measures used in planning (e.g., vīthī width selection) are structured as *8-tāla, 9-tāla, or 10-tāla daṇḍa types*, with selection conditioned by land extent (larger sites use larger daṇḍa categories). citeturn49view0

This is a fundamentally *relative* proportional system: absolute lengths depend on the chosen human module.

=== Sample proportional layout using tālamāna


Assumption (explicit): choose a representative householder height *H = 1.70 m* (for illustration only; the text defines tāla relative to the actual patron). citeturn49view0

Then:
- *1 tāla = H = 1.70 m*
- *8-tāla daṇḍa = 8H = 13.6 m*
- *9-tāla daṇḍa = 9H = 15.3 m*
- *10-tāla daṇḍa = 10H = 17.0 m*

If a design rule asks for a boundary band or vīthī-width in daṇḍa units, the designer chooses the daṇḍa type based on site class (“extended land → use 10; medium → 9; small/ordinary → 8” as summarized in the passage). citeturn49view0

=== Tālamāna measurement table and conversion examples


The four requested sources, in the passages cited here, *do not fully define a complete absolute unit ladder (aṅgula→hasta→daṇḍa, etc.)*; instead, they (a) use standard architectural units like *hasta (“cubit”) and aṅgula (“digit”)* in Bṛhat Saṃhitā house-dimension rules, and (b) define *tāla* relative to the patron and build *daṇḍa* types from tāla-counts in Mānuṣyālaya Candrikā commentary. citeturn46view0turn49view0

Accordingly, the most rigorous table available from these citations is the *relative tāla→daṇḍa* ladder:

#table(
  columns: 3,
  [*Unit*], [*Definition in cited passages*], [*Example if H=1.70 m*],
  [tāla], [householder’s height (gṛhakartṛ-puruṣa-samotsedha) citeturn49view0], [1.70 m],
  [daṇḍa (8-tāla)], [8 tāla (for smaller/ordinary scale) citeturn49view0], [13.6 m],
  [daṇḍa (9-tāla)], [9 tāla (medium scale) citeturn49view0], [15.3 m],
  [daṇḍa (10-tāla)], [10 tāla (larger scale) citeturn49view0], [17.0 m],
)



If you need an *aṅgula/hasta* ladder and metric conversions with primary citations from Mānasāra/Māyamata measurement chapters, those require additional direct textual extraction beyond what is cited in this session.

== Zone × Deity × Graha × Function matrix


=== What can be grounded in the four sources vs what must be flagged


The four sources (in the cited passages) strongly support:
- *Zone → Deity* mapping (especially Bṛhat Saṃhitā’s numbered squares; Mānuṣyālaya Candrikā’s mnemonic lists). citeturn47view4turn40view0
- *Functional meanings* in two senses:
  * (i) deity-domain meaning inherited from the deity’s identity (e.g., Varuṇa-water; Agni-fire), and
  * (ii) some explicit *architectural siting prescriptions* (e.g., cooking place in Parjanya/Śikhi/Vāyu zones in a Mānuṣyālaya Candrikā passage). citeturn38view1turn47view4
- *Graha correlations* are *not systematically assigned per zone* in the cited passages. The Mānuṣyālaya Candrikā commentary does, however, explicitly connect certain *yoni types to grahas* (e.g., gaja-yōni with Budha; vṛṣa-yōni with Śani, and a Kashyapa-śilpa mapping for a set of yonis), which can be used only as a *partial* basis for a “graha” column. citeturn37view3turn50view2

Therefore, the matrix below uses:
- *Zone and Deity*: Bṛhat Saṃhitā placements (most explicit). citeturn47view4turn47view0
- *Graha*:
  * “Direct graha” if the deity is itself a graha-name (Sūrya, Soma). citeturn47view4
  * Otherwise “Not specified in these four sources (in cited passages).”
- *Function/Activity*:
  * “Fire/water/air” etc for deities with universal domain identities, and
  * where available, a *classical siting note* from Mānuṣyālaya Candrikā (e.g., kitchen) flagged.

=== Matrix table


For space, this matrix lists *the 32 perimeter zones* (because these are the sectors most often used for entrance siting and perimeter zoning in classical passage discussions) plus *the Brahmā-sthāna* as a single central zone.

#table(
  columns: 5,
  [*Zone*], [*(x,y)*], [*Deity*], [*Graha correlation*], [*Primary function / activity*],
  [E1], [(9,9)], [Agni/Śikhi], [Not specified (as graha); fire deity], [Fire, heat, transformation; *kitchen/fire activities are classically linked to fire zones in later practice; one text passage links cooking to Parjanya/Śikhi/Vāyu zones* citeturn47view4turn38view1],
  [E2], [(9,8)], [Parjanya], [Not specified], [Rain, nourishment; explicit cooking placement sometimes linked to Parjanya in Mānuṣyālaya Candrikā commentary passage citeturn47view4turn38view1],
  [E3], [(9,7)], [Jayanta], [Not specified], [Victory/auspicious force (name-based domain)],
  [E4], [(9,6)], [Indra], [Not specified], [Royal power, command (Indra-domain)],
  [E5], [(9,5)], [Sūrya], [**Graha: Sun**], [Light, authority, vitality citeturn47view4],
  [E6], [(9,4)], [Satyā], [Not specified], [Truth/order; ethics/satya domain],
  [E7], [(9,3)], [Bhṛśa], [Not specified], [Protective force (vāstu tradition deity-name) citeturn47view4],
  [E8], [(9,2)], [Antarikṣa], [Not specified], [Intermediate space/sky band],
  [S1], [(9,1)], [Vāyu], [Not specified], [Air, movement; cooking placement sometimes linked to Vāyu in Mānuṣyālaya Candrikā passage citeturn47view4turn38view1],
  [S2], [(8,1)], [Pūṣa], [Not specified], [Nourishment/protection (Pūṣan-domain) citeturn47view4],
  [S3], [(7,1)], [Vitatha], [Not specified], [Vāstu-perimeter deity domain (textual name) citeturn47view4],
  [S4], [(6,1)], [Bṛhatkṣata], [Not specified], [Vāstu-perimeter deity domain citeturn47view4],
  [S5], [(5,1)], [Yama], [Not specified], [Restraint, death/time (Yama-domain) citeturn47view4],
  [S6], [(4,1)], [Gandharva], [Not specified], [Arts/music; intermediary beings citeturn47view4],
  [S7], [(3,1)], [Bhṛṅgarāja], [Not specified], [Vāstu-perimeter deity domain citeturn47view4],
  [S8], [(2,1)], [Mṛga], [Not specified], [Animal/wildlife domain marker citeturn47view4],
  [W1], [(1,1)], [Pitṛ], [Not specified], [Ancestors; funerary/lineage domain citeturn47view4],
  [W2], [(1,2)], [Dauvārika], [Not specified], [Gatekeeper/door-control domain (name) citeturn47view4],
  [W3], [(1,3)], [Sugrīva], [Not specified], [Guardian/strength domain (name) citeturn47view4],
  [W4], [(1,4)], [Kusumadanta], [Not specified], [Ornamentation/“flower-tooth” name-domain citeturn47view4],
  [W5], [(1,5)], [Varuṇa], [Not specified], [Water, storage; water-related siting is typical in later practice; deity is water-lord citeturn47view4],
  [W6], [(1,6)], [Asura], [Not specified], [Power/contest domain],
  [W7], [(1,7)], [Śeṣa], [Not specified], [Serpent/earth-support domain citeturn47view4],
  [W8], [(1,8)], [Pāpayakṣmā], [Not specified], [Disease/inauspiciousness marker citeturn47view4],
  [N1], [(1,9)], [Roga], [Not specified], [Disease marker citeturn47view4],
  [N2], [(2,9)], [Ahi], [Not specified], [Serpent domain],
  [N3], [(3,9)], [Mukhya], [Not specified], [Chief/primary domain (name) citeturn47view4],
  [N4], [(4,9)], [Bhallāṭa], [Not specified], [Vāstu deity marker citeturn47view4],
  [N5], [(5,9)], [Soma], [**Graha: Moon** (Soma/Chandra)], [Cooling, mind/fluids; lunar domain citeturn47view4],
  [N6], [(6,9)], [Bhujaga], [Not specified], [Serpent domain citeturn47view4],
  [N7], [(7,9)], [Aditi], [Not specified], [Mother-of-gods domain citeturn47view4],
  [N8], [(8,9)], [Diti], [Not specified], [Mother-of-daityas domain citeturn47view4],
  [Center], [(4–6,4–6)], [Brahmā (central 3×3)], [Not specified], [“Seat of Brahmā” requiring special care; treated as sensitive central zone citeturn47view0turn46view0],
)



If you need the same matrix expanded to *all 12 inner deities* (with Bṛhat Saṃhitā square numbers and coordinates), those deities are already enumerated above; the key limitation is that *graha correlations are not systematically provided per deity-zone* in the cited classical passages, except indirectly through yoni/graha discussions. citeturn47view0turn37view3turn50view2

== Short bibliography of cited primary witnesses and critical/translation streams


Bṛhat Saṃhitā (Varāhamihira). *Vāstuvidyā* chapter: English translation stream with square-numbered deity placement and body-part mapping. citeturn47view4turn47view0turn46view0

Bṛhat Saṃhitā (Varāhamihira). *Vāstuvidyā* chapter, Sanskrit text view: verses for vāstuvidyā opening and 81-square division (ekāśīti-vibhāga). citeturn48view0

Mānuṣyālaya Candrikā (Nīlakaṇṭhanmūṣat). Edition with Sanskrit ślokas and explanatory commentary, including (a) outer-32 and inner-deity mnemonic lists, (b) marma doctrine and avoidance rules, (c) tāla/daṇḍa proportional definitions, and (d) Āyādi formula tables and discussion. citeturn40view0turn39view0turn49view0turn50view2turn38view1

Mānasāra. “Architecture of Manasara” full-text witness: includes the Paramaśāyikā (81) line-drawing description, deity assignment sequences, outside-corner demoness placements, and a cross-authority disagreement note explicitly referencing Mayamata and others. citeturn15view0turn15view4turn14view1
