#!/bin/bash
echo "=== Atlas 330 Status ==="
echo ""
echo "Kernel:"
systemctl --user status atlas-kernel --no-pager -l | grep -E "Active:|Main PID:|Error"
echo ""
echo "Sound:"
systemctl --user status atlas-sound --no-pager -l | grep -E "Active:|Main PID:|Error"
echo ""
echo "API:"
curl -s --max-time 2 localhost:5000/health && echo " (health ok)" || echo " (not responding)"
echo ""
echo "Log (last 5 lines):"
tail -5 ~/atlas_core/logs/kernel.log 2>/dev/null || echo "(no log yet)"
